### ISSUE TITLE
how to compute object proposals?

### ISSUE THREAD

**Issue by zjhdxh** [GuoleiSun/CountSeg#9]
hi,@GuoleiSun,I am confused that How to prepare the "pre-computed object proposals".
Hope to receive your reply!

**Comment by GuoleiSun** [comment]
Hi, in our paper, our use the pre-computed object proposals, following https://arxiv.org/abs/1804.00880

**Comment by zjhdxh** [comment]
"Weakly Supervised Instance Segmentation using Class Peak Response" this paper did not provide the pre-computed object proposals algorithm in their github, and the author also did not answer the issue https://github.com/ZhouYanzhao/PRM/issues/10.
I see you cite Convolutional oriented boundaries and Multiscale combinatorial grouping for image segmentation and object proposal generation, so which one do you use?
